### ISSUE TITLE
Launcher Apps do not show up in steam library

### ISSUE THREAD

**Issue by McTastytv** [moraroy/NonSteamLaunchers-On-Steam-Deck#25] opened 2023-05-20 16:38 UTC
The install process goes through fine and restarts steam but nothing shows up in my steam library. ( I'm trying to use Epic and BattleNet)

**Comment by ChefPooH** [comment] 2023-05-21 01:26
Also this is apparent on all versions of the source code.

**Comment by drewdah** [comment] 2023-05-21 01:51
Having the same problem with current release. Tried starting fresh and reinstalling, restarting etc.

**Comment by Agent7427** [comment] 2023-05-21 02:52
Same issue. Tried multiple times but nothing shows up in Steam. Tried a few times with just a single app. I've checked to make sure the files went into the correct install path (they did). I've tried moving the launcher apps to the microSD card as well. 
--
I am however running a good portion of Steam and any games I download off my microSD card. Is it possible that /home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers on the internal storage isn't working because of certain files being stored on the microSD? 
--
I didn't see any instructions to add anything as a non-steam app manually so I'm assuming the program tries to do that on it's own when it closes and restarts Steam.

**Comment by KittyOwens** [comment] 2023-05-21 18:36
Having the exact same issue. Can't seem to make it work at all

**Comment by drewdah** [comment] 2023-05-21 18:54
This may be a duplicate of https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/issues/2 that has a lot of comments and debugging from the author in it

**Comment by shinshilas** [comment] 2023-05-23 17:05
After factory reset of steamdeck still does not work. For me `vdf` python module was missing, so I had to:

1. Set sudo password (`passwd`)
2. Disable read-only filesystem (`sudo steamos-readonly disable`)
3. Install pip (`sudo pacman -S pip`)
4. Install vdf (`pip install vdf`)
5. Rerun script

I've no idea how anyone is getting this to work without any modifications to steamos

**Comment by guillaume-royer-dev** [comment] 2023-05-25 21:21
[shinshilas](https://github.com/shinshilas) comment answer worked for me.
Brand new steamdeck. Need to set sudo password and install VDF then this installer will work.

**Comment by moraroy** [comment] 2023-05-25 21:47
@shinshilas @guillaume-royer-dev yeah I figured as much, my whole goal was to avoid having anyone have to put in their sudo password to write to the vdf file, I'm going to be changing how the script writes to the .vdf file because this way doesn't seem to be the best way to do so. I wanted to avoid pip and avoid any modifications to steam os which is why I've done it this way. Alot of people seem to get it working right away while others have issues like yourselves. It's obvious to me I need to find a better way without user interaction.

**Closed** 2023-06-19 13:46 UTC
