### ISSUE TITLE
Steam Library entries not created

### ISSUE THREAD

**Issue by srcamarda** [moraroy/NonSteamLaunchers-On-Steam-Deck#111] opened 2023-08-08 12:57 UTC
Hello,

After running the scripts, the launchers appear to have been installed correctly, however the entries have not been added to Steam Library. Checked after a reboot and in desktop/game mode. Is there any log file I can get to help?

Thanks in advance.

![script](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/5217213/5f2ec59e-473a-4f85-918d-54c51ce7ba07)

![library](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/assets/5217213/e16db84f-e70b-4e72-8da5-941c7496b112)
(They are also not in the Uncategorized / "Sem Categoria" group)

**Comment by moraroy** [comment] 2023-08-09 03:20
@srcamarda can you send the log, its in the downloads folder

**Comment by srcamarda** [comment] 2023-08-09 13:14
Sure. Sorry I didn't realize the log was there.

So I decided to do a Fresh Start to get a clean log, and found another weird behavior. When trying to install again, it did not let me continue without filling a custom website link. The field was left blank and I pressed Ok, like before. The log for this is bellow:

[NonSteamLaunchers-install1.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/12302923/NonSteamLaunchers-install1.log)

Then I just put "google.com" and was able to continue. And here is the log for the install itself (no shortcut was created on this try also):

[NonSteamLaunchers-install2.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/12302938/NonSteamLaunchers-install2.log)

**Comment by moraroy** [comment] 2023-08-14 04:23
@srcamarda i believe this has been fixed with the latest updates to the .sh file can you confirm it is working on your end?

**Comment by yuri-becker** [comment] 2023-08-14 20:02
I have the same issue still even with the new update :(

**Comment by moraroy** [comment] 2023-08-15 01:32
@yuri-becker could you send the log i need to compare to the other ones, its in the downloads folder

**Comment by yuri-becker** [comment] 2023-08-15 07:00
Sure, here you go:

[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/12341893/NonSteamLaunchers-install.log)

Thank you for investigating this.

**Comment by srcamarda** [comment] 2023-08-15 23:39
> @srcamarda i believe this has been fixed with the latest updates to the .sh file can you confirm it is working on your end?

Hi @moraroy.  I switched my SSD so I tried again, and I can confirm that for me it's working now! The website link thing also worked normally. Thanks for the help!

**Comment by trackmastersteve** [comment] 2023-08-16 00:01
[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/12353831/NonSteamLaunchers-install.log)

Here is my log. I'm having this issue, even with the latest update. Thank you in advance for all of your hard work!

**Comment by moraroy** [comment] 2023-08-16 03:00
@trackmastersteve i just attempted a fix ,let me know, i just deleted a potential line of code that was creating this bug

**Comment by moraroy** [comment] 2023-08-16 03:01
@yuri-becker same for you as well let me know

**Comment by yuri-becker** [comment] 2023-08-16 08:32
> @yuri-becker same for you as well let me know

Still no luck, sorry

**Comment by yuri-becker** [comment] 2023-08-16 17:33
I just noticed that on the other user (the Steam deck has two steam accounts logged in) the entries are there.

**Comment by mrwertyy** [comment] 2023-08-17 09:01
My deck remains locked at epic login, very bad experience tbh

**Comment by yuri-becker** [comment] 2023-08-17 10:01
> Every time i try to log on epic in desktop mode or game mode my deck dies and nothing responds, very bad experience tbh, back to lutris, take care with this f** app, finally i do a hard reset, this app does something bad to my deck, great devs!

This is GitHub not Facebook - if you want your problem fixed, please create a separate issue describing your problem, what lead to it and how to possibly reproduce it.

We don't condone this tone here, and I am truly thankful for @moraroy sacrificing their spare time to develop something for the community, completely free of charge.

I would like to ask you to delete your comment and I will do the same, so the discussion of this very issue stays on topic.

**Comment by srcamarda** [comment] 2023-08-19 23:55
> I just noticed that on the other user (the Steam deck has two steam accounts logged in) the entries are there.

Now that you mentioned, I think I did have 2 accounts when I was having the issue, so this could be the cause.

**Comment by trackmastersteve** [comment] 2023-08-20 04:21
The Deck I was having issues on, originally had two accounts. The first was a dummy account to test all of the controls (because it was second hand). And the second account was the real one. But the first account was deleted. Maybe the first account still exists in the file system?

**Comment by winterfrost999** [comment] 2023-08-29 02:56
Hi,

Same issue for me. The installer works and restarts steam after installing the launchers but it doesn't show up in the steam library. I can't seem to find the installed launchers folder either.

**Comment by moraroy** [comment] 2023-08-30 04:38
@winterfrost999 home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh: line 164: /home/deck/.steam/root/compatibilitytools.d/GE-Proton8-13/proton: No such file or directory 



In your log it says you don't have the proton file. So it's not installing anything. Delete the "compatabilitytools.d" folder and install the latest proton GE either through proton upqt from the discovery store or through my script again. Once my script is ran again your installers will install. For some reason you are missing the proton file in that folder.

**Comment by winterfrost999** [comment] 2023-09-01 05:23
> 

Thanks a lot! It works for me (:

**Comment by Darkalll** [comment] 2023-11-12 09:35
Still not working for me after installing Proton-ge from discovery store

**Closed** 2024-01-31 02:26 UTC
