### ISSUE TITLE
Decky Loader Plugin broken, for now use version "00473d"

### ISSUE THREAD

**Issue by julianrios** [moraroy/NonSteamLaunchers-On-Steam-Deck#329] opened 2024-06-21 22:35 UTC
I'm having issues installing the PlayStation Plus App. Here's what happens:

I go to Game Launchers, toggle it on, and select install.
The installation happens instantly, and I get a notification saying it's installed.
However, I can't find the app anywhere.
My other plugins, like the Xbox, Netflix, and GeForce Apps, didn't install instantly but work fine.

I'm using:

Steam beta version 3.5.19
Decky Loader version 2.12.3 (prerelease channel)
NonSteamLaunchers version 1.0.0-084a22c

**Comment by moraroy** [comment] 2024-06-22 01:13
@julianrios ITS BROKEN , use older versions of plugin

**Comment by julianrios** [comment] 2024-06-22 03:56
Is there an easy way to rollback ? Didn’t see any option in decks loader other than maybe install via zip.

**Comment by moraroy** [comment] 2024-06-22 04:18
@julianrios yeah when you go into the testing store you should see a  full list of differetn versions to choose from....i think "00473d1" is working... the latest two build arent building for some reason... :/ not sure what i did wrong  tbh https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/527#issuecomment-2182137534

**Comment by julianrios** [comment] 2024-06-22 18:20
Thanks so I tried a few different versions sometimes it shows as installed but nothing is in the non steam section might just be the steam os breaking this now

**Comment by VictorCostaOliveira** [comment] 2024-06-22 19:48
> Thanks so I tried a few different versions sometimes it shows as installed but nothing is in the non steam section might just be the steam os breaking this now

Same issue here.

So to resolve temporally, u need to edit the .desktop file: https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/blob/main/NonSteamLaunchers.desktop#L4

For me, the v3.3 solved the problem and me install the Xbox Game Pass.

The `.desktop` stayed like this: `Exec=/bin/bash -c 'curl -Ls https://raw.githubusercontent.com/moraroy/NonSteamLaunchers-On-Steam-Deck/v3.3/NonSteamLaunchers.sh | nohup /bin/bash'`

You need edit this in the steam deck on desktop mode

**Comment by julianrios** [comment] 2024-06-23 13:17
Nice thanks! I’m using the plugin from the decky loader testing store but hopefully won’t run into any issues installing the desktop version also to run try this.

**Comment by moraroy** [comment] 2024-06-23 13:19
@VictorCostaOliveira please use latest as latest has alot of fixes, and is emudeck and steam rom manager compatible

**Comment by julianrios** [comment] 2024-06-23 14:41
I used the testing store since I didn’t see non steam launcher plugin available on the stable store for decks loader.

**Comment by VictorCostaOliveira** [comment] 2024-06-24 11:48
> @VictorCostaOliveira please use latest as latest has alot of fixes, and is emudeck and steam rom manager compatible

Ok. I will try the latest version again.

I had tried all versions(on Saturday) from the latest until the 3.3 and none has worked.

**Comment by jsaa** [comment] 2024-07-02 01:24
Apparently, the problem is still happening. I'm trying to install Epic Games, and it gets stuck at "Installing launcher 1 of 1," in an infinite loading loop. I tested both the latest version and "00473d1," and the problem occurs in both. I had to force restart, and after that, when I try to install again, it shows the notification saying it's installed, but the app doesn't appear anywhere. Any solution?

**Comment by jsaa** [comment] 2024-07-02 01:45
Update: I just tried with version "1aded71" and it worked. I had to do a "Start Fresh" first. Epic games is installed and the icon appeared.

**Comment by moraroy** [comment] 2024-07-02 01:51
@jsaa let's goo! Ok good!!! That's good news <3 that was the newest version just now correct?

**Comment by jsaa** [comment] 2024-07-02 01:59
> @jsaa let's goo! Ok good!!! That's good news <3 that was the newest version just now correct?

Yep, the timing was perfect 😂

**Comment by moraroy** [comment] 2024-07-02 04:02
@jsaa that's tight!! @julianrios I'll close this as fixed

**Closed** 2024-07-02 04:02 UTC
