### ISSUE TITLE
Launcher (uplay/ubisoft connect) not accessible/viewable on steam library

### ISSUE THREAD

**Issue by Excalibur9760** [moraroy/NonSteamLaunchers-On-Steam-Deck#133] opened 2023-10-17 12:51 UTC

**Comment by kurzonmorris** [comment] 2023-10-27 01:36
same issue, it says its trying to install uplay but they now using ubisoft connect, is it simply trying to download the wrong file?

**Comment by AlbertoSPJ** [comment] 2023-10-28 09:07
I can confirm that Uplay/Ubisoft Launcher is not installing. I have also checked installing in a separate path and is creating a folder without files.

**Comment by ahsansh88** [comment] 2023-10-29 02:53
I'm having the same issue. All the other launchers I selected installed correctly. Uplay/Ubisoft Connect does not appear in my steam library.

**Comment by garycwallen** [comment] 2023-10-31 14:21
Yup, same issue for me. I was looking to pivot to this after a full wipe. It looks like a Uplay <> UbisoftConnect depreciation

**Comment by moraroy** [comment] 2023-10-31 22:04
@Excalibur9760 @garycwallen @AlbertoSPJ @ahsansh88 @kurzonmorris 

 Hey guys thanks for reporting this, sorry I haven't been able to do any coding these past couple months. The reason why Uplay/Ubisoft Connect doesn't work...based on my testing. It seems the recent steam updates have changed something with the command "wget" which I use to grab the ubisoft connect launcher from the website. I'm able to download the launcher just fine manually. But I cannot automatically download the ubi file anymore in the script. My error log says that the website "ubi.il" doesn't have certificates to download from the ubisoft website anymore. This may be a Ubisoft server side issue. Or it seems the steam deck with its recent updates has not updated the certificates to download from their anymore. I'm still looking into the issue. In the meantime, if anyone can find me a reliable source for an alternative link to the actual ubisoft launcher, I'll gladly swap out the download link in the script.

**Comment by AlbertoSPJ** [comment] 2023-10-31 22:18
Thanks a lot for the answer! Hopa you can fix it soon! You are making an excellent work with the script.

**Comment by moraroy** [comment] 2023-11-05 01:55
@AlbertoSPJ @garycwallen @ahsansh88 @kurzonmorris just fixed ubisoft!!

**Closed** 2023-11-06 22:13 UTC
