### ISSUE TITLE
Launchers not added to Steam [Epic Games, UPlay]

### ISSUE THREAD

**Issue by xCloudy75** [moraroy/NonSteamLaunchers-On-Steam-Deck#108] opened 2023-08-06 12:53 UTC
I followed the instructions step by step, once the scrip completed it restarted steam but couldn't find Epic games in the library. I removed the launchers and tries to install again but nothing worked. restarted the steam deck and the issue still persist. I went to Campadata file and found epicgameslauncher.exe there but cant find it in steam library. so i added it manually to steam (add non steam game) and forced the input for compatibility when I lunched it opened but non of the controllers are running except touching the screen

**Comment by moraroy** [comment] 2023-08-06 12:59
@xCloudy75 can you send the log

**Comment by xCloudy75** [comment] 2023-08-06 14:11
attached
[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/12269754/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment] 2023-08-07 01:27
@xCloudy75  you may need to hit the "Start Fresh" button in order for it to go smoothly, for some reason in you log file it says NonSteamLaunchers folder was not "empty" meaning you had left over files in their for some reason. So hitting start fresh should fix your issue and then try and re install epic. ill look into the code more to see why this is happening.

**Comment by xCloudy75** [comment] 2023-08-07 17:21
the attached file above was after I did the Start Fresh button not before.

**Comment by xCloudy75** [comment] 2023-08-12 10:25
any updates?

**Comment by moraroy** [comment] 2023-08-12 10:29
@xCloudy75 hasn't had a chance to do much fixing yet as I've had work IRL will be working on this fix this weekend. No worries.

**Comment by moraroy** [comment] 2023-08-14 04:23
@xCloudy75 just pushed a fix for you brother to the .sh file let me know if youre still having the problem

**Comment by trackmastersteve** [comment] 2023-08-15 03:49
I'm having the same issue on latest version (2.99)

**Comment by trackmastersteve** [comment] 2023-08-15 03:50
[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/12341060/NonSteamLaunchers-install.log)

**Comment by trackmastersteve** [comment] 2023-08-15 23:56
I used 2.98 on one deck without issues (other than the EA app issue itself).  And I tried to install 2.98, as well as 2.99, on a second Deck. And I can't seem to get any launchers to even show up. The log above is from the second Deck with the issues.

**Comment by moraroy** [comment] 2023-08-16 02:34
@trackmastersteve so for you the launchers are indeed installing just not being added to steam correct?

**Comment by trackmastersteve** [comment] 2023-08-16 12:54
@moraroy that is correct!

**Comment by endthewar** [comment] 2023-10-06 22:24
Have the same issue with them installing but not showing up in steam - if I add them manually they nearly crash my deck - any fix?

**Comment by OlegGorb** [comment] 2023-10-07 06:14
the same
but i dont know where to find log file

**Comment by MC31** [comment] 2023-10-17 11:32
I am also facing this problem.  I have tried a few different fixes, but the launchers will not show up in Steam, no matter what I try.

**Comment by cwthand** [comment] 2024-01-05 16:29
After installing the EGS client using NSL, the EGS client was not displayed in the steam library. Reboots and installations did not help from the very beginning. I solved the problem this way - along the way (/home/deck/.local/share/Steam/steamapps/compatdata/) I deleted the Non Steam Launcher file as well as its config and started installing EGS again and after installation it was displayed in the Steam library.

**Comment by Aldinas** [comment] 2024-02-11 19:01
Just to add a bit more information to this as I've hit the same issue. Here's the steps I've taken and what I tried:

1. Manually downloaded v3.8 from releases.
2. Ran the script.
3. Performed a fresh start (I hadn't installed anything at this point but I figured better safe than sorry).
4.  Selected EA Games, GoG, Epic, Uplay
5. Waited for the install to complete. I got prompted to install the Gecko components for Proton/Wine so did that.
6. The install finished and dropped me at the EA launcher. I was able to log in and view games.
7. Opened Steam - No launchers were listed.
8. Closed and quite Steam, and relaunched it - Still no launchers showing.
9. Re-ran the script, it showed the launchers had been installed and their location, but I had no way to launch them easily. 
10. Rebooted and checked for launchers in Steam library in Deck mode - Still nothing.
11. Rebooted back to desktop, ran the Fresh start option to remove everything.
12. Downloaded the NonSteamLauncher executable from the main page of the github repo (This is the one that downloads the latest release itself, appears to also be using 3.8). 
13. Ran the install, this time only did GoG and Epic.
14. Install completed successfully, still nothing appearing in Steams non-steam games for the launchers. (log attached, see **NonSteamLaunchers-install_2ndTry.log**) [NonSteamLaunchers-install_2ndTry.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/14233637/NonSteamLaunchers-install_2ndTry.log)
15. Restarted Steam, still nothing. 
16. Re-ran the fresh start script to clean it all out. 
17. Checked the location cwthand mentioned above (/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLauncher) - It doesnt exist for me (assuming the clean start flattened it as to be expected). 
18. Ran another install, this time just for Gog
19. Same issue, the install works and steam was automatically restarted, but still no launchers. Log attached (NonSteamLaunchers-install_gogOnly.log) [NonSteamLaunchers-install_gogOnly.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/14233638/NonSteamLaunchers-install_gogOnly.log)
20. I deleted the config file that cwthand mentioned but that made no difference after a re-install. 

I took a browse through the logs but the only thing that really stood out for me was line **4348** in the **2nd Try log** and line **1941** in the **GoG Only log**, where if I'm reading it correctly it has trouble interpreting my steam id timestamp and reports no users found, but the next few lines down it does list a steam ID but prefaces it with a **-** symbol, where it then struggles to create the appropriate shortcuts I think, I'm not super familiar with steams shortcuts/directory structure so I could be wrong. 

If you take a look at the GoG Only log and go from line 1940 all the way down to about 1968, you'll see the errors I'm referring to. 

```
+ mkdir /home/deck/.steam/root/userdata/-76561197960265728/config/
mkdir: cannot create directory ‘/home/deck/.steam/root/userdata/-76561197960265728/config/’: No such file or directory
+ touch /home/deck/.steam/root/userdata/-76561197960265728/config/shortcuts.vdf
touch: cannot touch '/home/deck/.steam/root/userdata/-76561197960265728/config/shortcuts.vdf': No such file or directory
+ config_dir=/home/deck/.steam/root/userdata/-76561197960265728/config/
+ shortcuts_vdf_path=/home/deck/.steam/root/userdata/-76561197960265728/config//shortcuts.vdf
```

**Comment by moraroy** [comment] 2024-02-13 04:49
@Aldinas interesting thank you ill take a look

**Comment by Aldinas** [comment] 2024-02-13 19:34
@moraroy - I've been doing some digging in the code and while my bash is rusty as anything, I think the problem is because I've got a very very old steam account that has a space in the username (i.e. my username is "Aldinas 2k").

Valve disallowed this in later account creations but those of us who made our accounts way back when Half Life 2 first released didn't have that restriction. 

The error I was seeing (` ((: 2k: value too great for base (error token is "2k")`) is referring to that 2k in my username as an invalid token because its expecting the timestamp, but getting the wrong value due to the space. 

I'll do some more testing and see if I can write a fix for it.

**Comment by Aldinas** [comment] 2024-02-13 21:18
I've put together a fix and submitted PR #208 for it. I don't think it will resolve trackmastersteves  issues as his log indicates his username and steam ID were correctly identified it, I think it might just be for a small percentage of people that have the same space in the username issue that I do.

**Comment by Kayonne** [comment] 2024-04-01 14:30
The first time I installed NSL it worked like a charm but recently I decided to factory reset my Deck and now I'm having issues. I'm trying to install the 'Battle.net' app and after it finishes downloading the app, I think it tries to add the shortcut (or something else) to Steam but for some reason it doesn't work and the Steam app closes and once it is opened again, everything else closes (related to NSL) and nothing happens nor does the app seems to have been installed. Any suggestions?

**Comment by moraroy** [comment] 2024-04-01 22:48
@Kayonne when you install the battlenet launcher make sure you close the windows and let it install twice

**Comment by Matthewruth71** [comment] 2024-04-28 09:46
For anyone having this issue in the future: 
if you have already installed an app before and maybe after trying to reinstall an app,  this issue comes up .
you basically just need to delete the "nonsteamlauncher" file , from the folder "Compdata" (the path should be home/local/share/steam/steamapps/compdata).
After this , try again installing the app you want.
This should solve the issue completely and install any app without any problem .
The issue is just an internal conflict inside the compdata folder, pretty simple.

At least , this has always been the fix for me.

**Comment by Mobeeuz** [comment] 2024-05-14 04:34
I deleted the modules folder, tried again, same results. A reboot showed NSL not detecting the GOG install that it created.

[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/15302614/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment] 2024-05-14 05:10
@Mobeeuz very strange I can't seem to duplicate that error. I'm going to try on a fresh steam deck, I will get back to you. In the mean time I recommend using the decky plug-in version of NonSteamLaunchers, the decky plug-in doesn't deal in vdf file parsing.

**Comment by Mobeeuz** [comment] 2024-05-14 14:41
I did, I get the "Something went wrong, refresh" black screen error during client installation and it crashes.

**Comment by moraroy** [comment] 2024-05-14 21:17
@Mobeeuz you got that with the decky plugin??

**Comment by Mobeeuz** [comment] 2024-05-15 02:34
Yes, NSL is the only plugin with that issue that I have installed. It's full screen, stops the entire process during client installation, and crashes Decky entirely.

**Comment by moraroy** [comment] 2024-05-15 02:55
@Mobeeuz dang :/ ok will keep testing, thanks for letting me know.

**Comment by Mobeeuz** [comment] 2024-05-15 14:57
Is this for Desktop mode install or the Decky install? If it's for Desktop, the last log I sent was the last attempt I made.

**Comment by Mobeeuz** [comment] 2024-05-16 03:51
Tried, failed, no log in downloads folder. Error was 'autorun'

**Comment by moraroy** [comment] 2024-05-16 04:18
@Mobeeuz add me on discord @moraroy

**Comment by suttin** [comment] 2024-05-16 19:31
I wanted to throw my hat in too. I factory reset my Deck this morning, heard about your project and wanted to give it a go. Script was the second thing installed on my Deck after Firefox.

[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/15339999/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment] 2024-05-16 19:36
@suttin cool thanks suttin that error is because you have no shortcuts.vdf file, aince.you don't have any shortcuts in your library I've already fixed this in the plug-in version on decky. Still haven't fixed this one yet in the .desktop version. I would simply add something to steam manually, and then try it.

**Comment by moraroy** [comment] 2024-06-22 13:02
@suttin this has now been fixed

**Closed by moraroy** 2024-06-22 13:02 UTC
Labels: bug

**Comment by Mobeeuz** [comment] 2024-06-30 07:45
Logs as requested...
[Archive.zip](https://github.com/user-attachments/files/16043622/Archive.zip)
