### ISSUE TITLE
Frozen during installations of launchers.

### ISSUE THREAD

**Issue by WolfSc84** [moraroy/NonSteamLaunchers-On-Steam-Deck#31] opened 2023-05-30 02:13 UTC
Frozen during installation, specifically while installing GOG launcher. It does not continue and freezes at that step.

**Comment by WolfSc84** [comment] 2023-05-30 02:20
This is the log attached to  this fail:

2023-05-29 21:17:29 (12.0 MB/s) - ‘/home/deck/Downloads/NonSteamLaunchersInstallation/GOG_Galaxy_2.0.exe’ saved [983624/983624]

+ echo 'Running EXE file using Proton without the /passive option'
+ echo 45
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton8-3/proton run /home/deck/Downloads/NonSteamLaunchersInstallation/GOG_Galaxy_2.0.exe
+ echo '# Downloading & Installing Gog Galaxy...Please wait...'
+ true
+ pgrep -f GalaxySetup.tmp
+ sleep 1
Proton: Upgrading prefix from None to GE-Proton8-3 (/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/)
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton8-3/proton", line 1833, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton8-3/proton", line 1616, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton8-3/proton", line 795, in setup_prefix
    os.symlink("../drive_c", self.prefix_dir + "/dosdevices/c:")
FileNotFoundError: [Errno 2] No such file or directory: '../drive_c' -> '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx//dosdevices/c:'
+ true
+ pgrep -f GalaxySetup.tmp
+ sleep 1
+ true
+ pgrep -f GalaxySetup.tmp
+ sleep 1
+ true

**Comment by moraroy** [comment] 2023-05-30 04:47
@WolfSc84 did you move any launchers to the sd card

**Comment by WolfSc84** [comment] 2023-05-30 17:41
no i didn't... is my first time installing the tool... i downloaded the zip into the download folder and then execute the .desktop file... during the installation is frozen specifically during GOG installation

**Comment by moraroy** [comment] 2023-05-30 20:26
@WolfSc84 ah I see... ok.OK.. thanks for letting me know I'll take a look at what's going on

**Comment by moraroy** [comment] 2023-05-30 21:50
@WolfSc84 could you send me the full log.. it sounds like a folder wasnt created before it started downloading the gog launcher.... i was unable to replicate this bug on my system. but it should be a simple fix once i see the full log

**Comment by WolfSc84** [comment] 2023-05-31 03:30
[NonSteamLaunchers-install.log](https://github.com/moraroy/NonSteamLaunchers-On-Steam-Deck/files/11608358/NonSteamLaunchers-install.log)

**Comment by WolfSc84** [comment] 2023-05-31 03:31
just let me know anything else 😁

**Comment by LiamDawe** [comment] 2023-05-31 15:20
Looks like the issue is possibly to do with the GE-Proton install, relevant bits from the log:

```
+ cd /home/deck/.steam/root/compatibilitytools.d/GE-Proton8-3
+ export 'STEAM_COMPAT_CLIENT_INSTALL_PATH=~/.local/share/Steam'
+ STEAM_COMPAT_CLIENT_INSTALL_PATH='~/.local/share/Steam'
+ export STEAM_COMPAT_DATA_PATH=/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers
+ STEAM_COMPAT_DATA_PATH=/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers
+ '[' '!' -f /home/deck/Downloads/NonSteamLaunchersInstallation/GOG_Galaxy_2.0.exe ']'
+ echo 'Running EXE file using Proton without the /passive option'
+ echo 45
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton8-3/proton run /home/deck/Downloads/NonSteamLaunchersInstallation/GOG_Galaxy_2.0.exe
+ echo '# Downloading & Installing Gog Galaxy...Please wait...'
+ true
+ pgrep -f GalaxySetup.tmp
+ sleep 1
Proton: Upgrading prefix from None to GE-Proton8-3 (/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/)
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton8-3/proton", line 1833, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton8-3/proton", line 1616, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton8-3/proton", line 795, in setup_prefix
    os.symlink("../drive_c", self.prefix_dir + "/dosdevices/c:")
FileNotFoundError: [Errno 2] No such file or directory: '../drive_c' -> '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx//dosdevices/c:'
```

**Comment by moraroy** [comment] 2023-05-31 21:03
@LiamDawe hey Liam! Thank you so much for the shout out on the articles and video it means alot!! I hope I was able to do that pull request you did last night correctly. I wasn't sure at first if it went through but it looked like it did. Thank for everything! Regarding these launchers, some of them arent behaving correctly and most likely due to the proton version GE-Proton8-3, unfortunately I haven't been able to recreate any of the launchers failing on my deck or system. It may have to do with proton ge plus a networking issue.

**Comment by WolfSc84** [comment] 2023-06-01 01:35
I tried minutes ago in my linux pc and works properly using proton GE 8.3.. i dont know why is falling on my steam deck so im going to debug the process and let you know if i find the cause of the issue

**Comment by moraroy** [comment] 2023-06-01 01:59
@WolfSc84 was ge proton already installed when it ran the script? if so, it may have been installed incorrectly or have corruption. if this is the first time you have had it installed by my script this is interesting because it means that proton isnt setting up the files necessary to install anything.

**Comment by WolfSc84** [comment] 2023-06-01 16:58
yes was installed using proton-qt app... yesterday i found a way checking the options separate apps ids. that option download a version of proton qt individually but fails the executables on the steam shorcuts... the issue is that the installer doesnt recognice the proton version installed with proton-qt app, and if you check the option separate ids on the installer fails the shortcuts due steam doesnt recognice the proton version downloaded by the installer and the path of the executables

**Comment by joesyuh** [comment] 2023-06-03 22:48
I am having this issue but only when doing battle.net. I will upload my log when I figure out how...

**Comment by joesyuh** [comment] 2023-06-06 12:53
The issue, for me, is resolved with the newest version as of 6/5/2023.

**Closed** 2023-06-19 13:43 UTC
